SELECT DISTINCT(CEDULA), NOMBRE, ROLUNIANDINO
FROM
(SELECT DISTINCT(CEDULA), NOMBRE, ROLUNIANDINO
FROM (CLIENTE FULL OUTER JOIN RESERVA 
ON CLIENTE.CEDULA=RESERVA.IDCLIENTE)
FULL OUTER JOIN RESERVASDEALOJAMIENTO ON RESERVA.IDRESERVA=RESERVASDEALOJAMIENTO.IDRESERVA
MINUS
SELECT DISTINCT(CEDULA), NOMBRE, ROLUNIANDINO
FROM (CLIENTE JOIN RESERVA 
ON CLIENTE.CEDULA=RESERVA.IDCLIENTE)
JOIN RESERVASDEALOJAMIENTO ON RESERVA.IDRESERVA=RESERVASDEALOJAMIENTO.IDRESERVA
WHERE IDALOJAMIENTO > 1000 AND FECHARESERVA BETWEEN '05/01/2017' AND '05/01/2018')
ORDER BY CEDULA, NOMBRE, ROLUNIANDINO;

SELECT DISTINCT(CEDULA)
FROM
(SELECT DISTINCT(CEDULA), NOMBRE, ROLUNIANDINO
FROM ((CLIENTE LEFT JOIN RESERVA ON CLIENTE.CEDULA=RESERVA.IDCLIENTE)
LEFT JOIN RESERVASDEALOJAMIENTO ON RESERVA.IDRESERVA=RESERVASDEALOJAMIENTO.IDRESERVA)
LEFT JOIN ALOJAMIENTO ON RESERVASDEALOJAMIENTO.IDALOJAMIENTO=ALOJAMIENTO.IDALOJAMIENTO
MINUS
SELECT DISTINCT(CEDULA), NOMBRE, ROLUNIANDINO
FROM ((CLIENTE INNER JOIN RESERVA ON CLIENTE.CEDULA=RESERVA.IDCLIENTE)
INNER JOIN RESERVASDEALOJAMIENTO ON RESERVA.IDRESERVA=RESERVASDEALOJAMIENTO.IDRESERVA)
INNER JOIN ALOJAMIENTO ON RESERVASDEALOJAMIENTO.IDALOJAMIENTO=ALOJAMIENTO.IDALOJAMIENTO
WHERE (ALOJAMIENTO.IDALOJAMIENTO = 16641) AND (FECHARESERVA BETWEEN '05/01/2016' AND '06/01/2019') AND IDOPERADOR=2)
ORDER BY CEDULA;